uploads = []
generated = []

[[outputs]]
id = "arc_kGMIYF29Wg532JZPl"
uri = "file://wi-estate-cleanout-site.zip"
type = "unspecified"
title = "WI Estate Cleanout — Static Site"

[[outputs]]
id = "ZQpnVPUecJ2J8w8z9tXI1"
uri = "file://wi-appliance-disposal-site.zip"
type = "unspecified"
title = "WI Appliance Disposal — Static Site"

[[outputs]]
id = "4stTk16GVHVr59ggFxlmw"
uri = "file://artifacts/wi-furniture-disposal/wi-furniture-disposal-full-site.zip"
type = "unspecified"
title = "WI Furniture Disposal — Full Site"

[[outputs]]
id = "QOiX2GfbbRVDQ-Dh-A4Si"
uri = "file://artifacts/wi-mattress-disposal/wi-mattress-disposal-full-site.zip"
type = "unspecified"
title = "WI Mattress Disposal — Full Site"

[[outputs]]
id = "7F48wjYhtInXchH9ySnhZ"
uri = "file://jgestates-com.zip"
type = "unspecified"
title = "JG Estates — Site Files"

[[outputs]]
id = "1tg-lMgPUQ25tm690kcI3"
uri = "file://jgestates-com-site.zip"
type = "unspecified"
title = "JG Estates – Full Site (72 pages, updated service areas)"
